# Setup
name:         Cyril's Blog
tagline:      Amateur coder // Good at Ctrl+V // "Write the bug, destroy the world" //
baseurl:      "https://delicate-band-9327.on.fleek.co/"
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
